[project]
name = "subscription-cli"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "ziyun", email = "3561900938@qq.com" }
]
requires-python = ">=3.13"
dependencies = [
    "rich>=15.0.0",
]

[project.scripts]
subscription-cli = "subscription_cli:main"

[build-system]
requires = ["uv_build>=0.12.18,<0.13.0"]
build-backend = "uv_build"
